In [1]:
import numpy as np

In [2]:
states = ["Rainy", "Sunny"]
n_states = len(states)

observations = ["walk", "shop", "clean"]
n_observations = len(observations)

# initial probability
phi = np.array([0.6, 0.4])

# transition probability
A = np.array([[0.7, 0.3],
              [0.4, 0.6]])

# observation probability
B = np.array([[0.2, 0.3, 0.5],
              [0.5, 0.4, 0.1]])

# Tiga permasalahan di HMM
1. Evaluation, masukannya Observation (O) dan lambda (phi, A, B) -> likelihood P(O | lambda)
2. Decoding, masukannya Observation (O) dan lambda -> State sequence S = {S1, S2, ..., Sn}
3. Learning, masukannya Observation (O) -> return phi, A, B terbaik berdasarkan nilai likelihood P(O | lambda)

# hmmlearn

In [3]:
from hmmlearn import hmm

In [4]:
# initialize hmm
m_hmmlearn = hmm.MultinomialHMM(n_components=n_states)
m_hmmlearn.startprob = phi
m_hmmlearn.transmat = A
m_hmmlearn.emissionprob = B

In [5]:
# observation sequence
obs_seq = np.array([[0, 2, 1, 0, 1, 0, 0]])

In [6]:
# learning
m_hmmlearn = m_hmmlearn.fit(obs_seq)

In [7]:
m_hmmlearn.startprob_

array([1.00000000e+00, 3.53114448e-14])

In [8]:
m_hmmlearn.transmat_

array([[5.00876766e-03, 9.94991232e-01],
       [9.99731826e-01, 2.68174270e-04]])

In [9]:
m_hmmlearn.emissionprob_

array([[4.99940586e-01, 5.00059414e-01, 9.70104025e-15],
       [6.66719462e-01, 9.73064424e-09, 3.33280529e-01]])

In [10]:
log_prob, best_path = m_hmmlearn.decode(obs_seq.T, algorithm='viterbi')

In [11]:
log_prob

-4.697999994816159

In [12]:
best_path

array([0, 1, 0, 1, 0, 1, 0])

# pomegranate

In [13]:
from pomegranate import *

In [14]:
# initialize hmm
m_pomegranate = HiddenMarkovModel()

# definisikan state
rainy = State(DiscreteDistribution({'walk': 0.2, 'shop': 0.3, 'clean': 0.5}), name='Rainy')
sunny = State(DiscreteDistribution({'walk': 0.5, 'shop': 0.4, 'clean': 0.1}), name='Sunny')

# initial probability
m_pomegranate.add_transition(m_pomegranate.start, rainy, 0.6)
m_pomegranate.add_transition(m_pomegranate.start, sunny, 0.4)

# transition probability
m_pomegranate.add_transition(rainy, rainy, 0.7)
m_pomegranate.add_transition(rainy, sunny, 0.3)
m_pomegranate.add_transition(sunny, rainy, 0.4)
m_pomegranate.add_transition(sunny, sunny, 0.6)

m_pomegranate.bake()

In [15]:
# observation sequence
obs_seq_str = ['walk', 'clean', 'shop', 'walk', 'shop', 'walk', 'walk']

In [16]:
m_pomegranate.predict(obs_seq_str)

[1, 0, 0, 1, 1, 1, 1]

In [17]:
m_pomegranate.log_probability(obs_seq_str)

-7.709129800619791

# Latihan
- States = Sunny, Rainy, Cloudy, Foggy
- Observations = Umbrella, Not Umbrella